# Generated by Django 2.2 on 2019-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('map_state', models.CharField(max_length=255)),
            ],
        ),
    ]
