# Generated by Django 2.2 on 2019-04-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('uuid', models.CharField(max_length=255)),
                ('mapState', models.CharField(max_length=255)),
            ],
        ),
    ]
