# Generated by Django 2.2 on 2019-04-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='map_original',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='map_state',
            field=models.TextField(),
        ),
    ]
