# Generated by Django 2.2 on 2019-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
