# Generated by Django 2.2 on 2019-04-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20190419_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
